# frozen_string_literal: true

source "https://rubygems.org"
ruby "2.4.2"

gem "activerecord"
gem "app_konfig"
gem "bootstrap"
gem "haml"
gem "httparty"
gem "pg"
gem "pry"
gem "puma"
gem "rake"
gem "sass"
gem "sidekiq"
gem "sinatra"
gem "sinatra-activerecord"
gem "sinatra-contrib"
gem "sprockets"
gem "uglifier"
