defaults: &defaults
  redis:
    url: "redis://localhost:6379"
  rollbar:
    access_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>

development:
  <<: *defaults
  newrelic:
    license_key: ""
  slack:
    api_token: ""
    incoming_webhook_url: ""

staging:
  <<: *defaults
  authentication:
    username: <%= ENV["AUTH_USERNAME"] %>
    password: <%= ENV["AUTH_PASSWORD"] %>
  newrelic:
    license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  redis:
    url: <%= ENV["REDISTOGO_URL"] %>
  sidekiq:
    username: <%= ENV["SIDEKIQ_USERNAME"] %>
    password: <%= ENV["SIDEKIQ_PASSWORD"] %>
  slack:
    api_token: <%= ENV["API_TOKEN"] %>
    incoming_webhook_url: <%= ENV["INCOMING_WEBHOOK_URL"] %>
    users_api_endpoint: "https://slack.com/api/users.info"

production:
  <<: *defaults
  authentication:
    username: <%= ENV["AUTH_USERNAME"] %>
    password: <%= ENV["AUTH_PASSWORD"] %>
  newrelic:
    license_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  redis:
    url: <%= ENV["REDISTOGO_URL"] %>
  sidekiq:
    username: <%= ENV["SIDEKIQ_USERNAME"] %>
    password: <%= ENV["SIDEKIQ_PASSWORD"] %>
  slack:
    api_token: <%= ENV["API_TOKEN"] %>
    incoming_webhook_url: <%= ENV["INCOMING_WEBHOOK_URL"] %>
    users_api_endpoint: "https://slack.com/api/users.info"
