development:
  slack:
    api_token: ""
    channel_webhook_url: ""
    incoming_webhook_url: ""

production:
  slack:
    api_token: <%= ENV["API_TOKEN"] %>
    channel_webhook_url: <%= ENV["CHANNEL_WEBHOOK_URL"] %>
    incoming_webhook_url: <%= ENV["INCOMING_WEBHOOK_URL"] %>
