development:
  slack:
    api_token: ""
    incoming_webhook_url: ""

production:
  redis:
    url: <%= ENV["REDISTOGO_URL"] %>
  slack:
    api_token: <%= ENV["API_TOKEN"] %>
    incoming_webhook_url: <%= ENV["INCOMING_WEBHOOK_URL"] %>
